"use strict";

/** @type {import('sequelize-cli').Migration} */
module.exports = {
  up: (queryInterface, Sequelize) => {
    let items = [
      { province: "SG", places: "Trạm Xăng Dầu Huệ Thiên 3" }, //SG - BTh
      { province: "SG", places: "Cầu Vượt Sóng Thần" },
      { province: "SG", places: "Chợ Tam Bình" },
      { province: "SG", places: "Ngã 4 Gò Dưa" },
      { province: "SG", places: "Cầu vượt Linh Xuân" },
      { province: "SG", places: "Khu Chế Xuất Linh Trung" },
      { province: "SG", places: "Đại học Nông Lâm" },
      { province: "SG", places: "Cây Xăng Hiệp Phú 2" },
      { province: "SG", places: "Ngã 3 Tân Vạn" },
      { province: "SG", places: "Cổng 11 - Vòng Xoay tránh Biên Hòa" },
      { province: "BTh", places: "Ngã ba 46 Bình Thuận" },
      { province: "BTh", places: "Ma Lâm" },
      { province: "BTh", places: "Lương Sơn" },
      { province: "BTh", places: "Bến xe Tuy Phong" },
      { province: "BTh", places: "Chí Công" },
      { province: "BTh", places: "Nội thành Phan Rí" },
      { province: "BTh", places: "Chợ Lầu" },
      { province: "BTh", places: "Cổ Thạch" },
      { province: "BTh", places: "Phước Thể" },
      { province: "NT", places: "Ngã 3 Phú Quý" },
      { province: "NT", places: "Trạm dừng chân Hạnh Vy" },
      { province: "NT", places: "Ngã 5 Phan Rang" },
      { province: "NT", places: "Chợ Phước Mỹ" },
      { province: "NT", places: "Ngã 4 Tháp Chàm" },
      { province: "NT", places: "Thôn Đắc Nhơn" },
      { province: "NT", places: "Chợ Lương Cang" },
      { province: "NT", places: "Nha Hố" },
      { province: "NT", places: "Đồng Mé" },
      { province: "NT", places: "UBND xã Mỹ Sơn" },
      { province: "NT", places: "Bến Xe Ninh Sơn" },
      { province: "NT", places: "Chợ Quảng Sơn" },
      { province: "NT", places: "Nhà thờ La Vang" },
      { province: "NT", places: "Trạm biến áp Ninh Sơn" },
      { province: "NT", places: "Cây xăng Phú Quỳnh*" },
      { province: "NT", places: "Trà Giang" },
      { province: "ĐL", places: "Ngã ba Duy Hoà" },
      { province: "ĐL", places: "Buôn Ma Thuột - Quốc Lộ 14" },
      { province: "ĐL", places: "Bến xe phía nam Buôn Mê Thuột" },
      { province: "ĐL", places: "Cư Kuin" },
      { province: "ĐL", places: "VP Hòa Đông-Tiến Oanh" },
      { province: "ĐL", places: "VP Hòa Thắng-Tiến Oanh" },
      { province: "ĐL", places: "VP Đạt Lý-Tiến Oanh" },
      { province: "ĐL", places: "TP Buôn Ma Thuột" },
      { province: "GL", places: "Ngã 3 Hàm Rồng" },
      { province: "GL", places: "Ngã 3 La Sơn" },
      { province: "GL", places: "Ngã 4 Lâm Nghiệp" },
      { province: "GL", places: "Đăk Sơ Mai" },
      { province: "GL", places: "Nội thành Pleiku" },
      { province: "GL", places: "Chợ Trà Bá" },
      { province: "GL", places: "Chư Păh" },
      { province: "GL", places: "ngã 3 Yaly" },
      { province: "GL", places: "Nội huyện An Khê" },
      { province: "GL", places: "Mang Yang" },
      { province: "GL", places: "Ngã 3 Phú Mỹ" },
      { province: "GL", places: "Bến xe Đức Long Gia Lai" },
      { province: "PY", places: "Nội Ô Thành Phố Tuy Hoà" },
      { province: "PY", places: "Thị Trấn Chí Thạnh" },
      { province: "PY", places: "VP Tuy Hoà" },
      { province: "BV", places: "Cây xăng Kim Hải" },
      { province: "BV", places: "Cổng chào Bà Rịa" },
      { province: "BV", places: "Nội thành Vũng Tàu" },
      { province: "AG", places: "Nội thành An Giang" },
      { province: "BL", places: "Nội thành Bạc Liêu" },
      { province: "BK", places: "Nội thành Bắc Kạn" },
      { province: "BG", places: "Nội thành Bắc Giang" },
      { province: "BN", places: "Nội thành Bắc Ninh" },
      { province: "BT", places: "Nội thành Bến Tre" },
      { province: "BD", places: "Nội thành Bình Dương" },
      { province: "BĐ", places: "Nội thành Bình Định" },
      { province: "BP", places: "Nội thành Bình Phước" },
      { province: "CM", places: "Nội thành Cà Mau" },
      { province: "CB", places: "Nội thành Cao Bằng" },
      { province: "CT", places: "Nội thành Cần Thơ" },
      { province: "ĐNa", places: "Nội thành Đà Nẵng" },
      { province: "ĐNo", places: "Nội thành Đắk Nông" },
      { province: "ĐB", places: "Nội thành Điện Biên" },
      { province: "ĐN", places: "Nội thành Đồng Nai" },
      { province: "ĐT", places: "Nội thành Đồng Tháp" },
      { province: "HG", places: "Nội thành Hà Giang" },
      { province: "HNa", places: "Nội thành Hà Nam" },
      { province: "HN", places: "Nội thành Hà Nội" },
      { province: "HT", places: "Nội thành Hà Tĩnh" },
      { province: "HD", places: "Nội thành Hải Dương" },
      { province: "HP", places: "Nội thành Hải Phòng" },
      { province: "HGi", places: "Nội thành Hậu Giang" },
      { province: "HB", places: "Nội thành Hòa Bình" },
      { province: "HY", places: "Nội thành Hưng Yên" },
      { province: "KH", places: "Nội thành Khánh Hoà" },
      { province: "KG", places: "Nội thành Kiên Giang" },
      { province: "KT", places: "Nội thành Kon Tum" },
      { province: "LC", places: "Nội thành Lai Châu" },
      { province: "LS", places: "Nội thành Lạng Sơn" },
      { province: "LCa", places: "Nội thành Lào Cai" },
      { province: "LĐ", places: "Nội thành Lâm Đồng" },
      { province: "LA", places: "Nội thành Long An" },
      { province: "NĐ", places: "Nội thành Nam Định" },
      { province: "NA", places: "Nội thành Nghệ An" },
      { province: "NB", places: "Nội thành Ninh Bình" },
      { province: "PT", places: "Nội thành Phú Thọ" },
      { province: "QB", places: "Nội thành Quảng Bình" },
      { province: "QNa", places: "Nội thành Quảng Nam" },
      { province: "QNg", places: "Nội thành Quảng Ngãi" },
      { province: "QN", places: "Nội thành Quảng Ninh" },
      { province: "QT", places: "Nội thành Quảng Trị" },
      { province: "ST", places: "Nội thành Sóc Trăng" },
      { province: "SL", places: "Nội thành Sơn La" },
      { province: "TN", places: "Nội thành Tây Ninh" },
      { province: "TB", places: "Nội thành Thái Bình" },
      { province: "TNg", places: "Nội thành Thái Nguyên" },
      { province: "TH", places: "Nội thành Thanh Hóa" },
      { province: "TTH", places: "Nội thành Thừa Thiên-Huế" },
      { province: "TG", places: "Nội thành Tiền Giang" },
      { province: "TV", places: "Nội thành Trà Vinh" },
      { province: "TQ", places: "Nội thành Tuyên Quang" },
      { province: "VL", places: "Nội thành Vĩnh Long" },
      { province: "VP", places: "Nội thành Vĩnh Phúc" },
      { province: "YB", places: "Nội thành Yên Bái" },
    ];
    items.forEach((item) => {
      item.createdAt = Sequelize.literal("NOW() ");
      item.updatedAt = Sequelize.literal("NOW() ");
    });
    return queryInterface.bulkInsert("Places", items);
  },

  down: (queryInterface, Sequelize) => {
    return queryInterface.bulkDelete("Places", null, {});
  },
};
