"use strict";

/** @type {import('sequelize-cli').Migration} */
module.exports = {
  up: (queryInterface, Sequelize) => {
    let items = [
      // ticket 5 idOwner 1 9seats 6/1/2023
      { idBooking: null, idTicket: 1, idUser: null },
      { idBooking: null, idTicket: 1, idUser: null },
      { idBooking: null, idTicket: 1, idUser: null },
      { idBooking: null, idTicket: 1, idUser: null },
      { idBooking: null, idTicket: 1, idUser: null },
      { idBooking: null, idTicket: 1, idUser: null },
      { idBooking: null, idTicket: 1, idUser: null },
      { idBooking: null, idTicket: 1, idUser: null },
      { idBooking: null, idTicket: 1, idUser: null },
      { idBooking: null, idTicket: 1, idUser: null },
      // ticket 5 idOwner 2 32seats 6/1/2023
      { idBooking: null, idTicket: 5, idUser: null },
      { idBooking: null, idTicket: 5, idUser: null },
      { idBooking: null, idTicket: 5, idUser: null },
      { idBooking: null, idTicket: 5, idUser: null },
      { idBooking: null, idTicket: 5, idUser: null },
      { idBooking: null, idTicket: 5, idUser: null },
      { idBooking: null, idTicket: 5, idUser: null },
      { idBooking: null, idTicket: 5, idUser: null },
      { idBooking: null, idTicket: 5, idUser: null },
      { idBooking: null, idTicket: 5, idUser: null },
      { idBooking: null, idTicket: 5, idUser: null },
      { idBooking: null, idTicket: 5, idUser: null },
      { idBooking: null, idTicket: 5, idUser: null },
      { idBooking: null, idTicket: 5, idUser: null },
      { idBooking: null, idTicket: 5, idUser: null },
      { idBooking: null, idTicket: 5, idUser: null },
      { idBooking: null, idTicket: 5, idUser: null },
      { idBooking: null, idTicket: 5, idUser: null },
      { idBooking: null, idTicket: 5, idUser: null },
      { idBooking: null, idTicket: 5, idUser: null },
      { idBooking: null, idTicket: 5, idUser: null },
      { idBooking: null, idTicket: 5, idUser: null },
      { idBooking: null, idTicket: 5, idUser: null },
      { idBooking: null, idTicket: 5, idUser: null },
      { idBooking: null, idTicket: 5, idUser: null },
      { idBooking: null, idTicket: 5, idUser: null },
      { idBooking: null, idTicket: 5, idUser: null },
      { idBooking: null, idTicket: 5, idUser: null },
      { idBooking: null, idTicket: 5, idUser: null },
      { idBooking: null, idTicket: 5, idUser: null },
      { idBooking: null, idTicket: 5, idUser: null },
      { idBooking: null, idTicket: 5, idUser: null },
      // ticket 9 idOwner 3 22seats
      { idBooking: null, idTicket: 9, idUser: null },
      { idBooking: null, idTicket: 9, idUser: null },
      { idBooking: null, idTicket: 9, idUser: null },
      { idBooking: null, idTicket: 9, idUser: null },
      { idBooking: null, idTicket: 9, idUser: null },
      { idBooking: null, idTicket: 9, idUser: null },
      { idBooking: null, idTicket: 9, idUser: null },
      { idBooking: null, idTicket: 9, idUser: null },
      { idBooking: null, idTicket: 9, idUser: null },
      { idBooking: null, idTicket: 9, idUser: null },
      { idBooking: null, idTicket: 9, idUser: null },
      { idBooking: null, idTicket: 9, idUser: null },
      { idBooking: null, idTicket: 9, idUser: null },
      { idBooking: null, idTicket: 9, idUser: null },
      { idBooking: null, idTicket: 9, idUser: null },
      { idBooking: null, idTicket: 9, idUser: null },
      { idBooking: null, idTicket: 9, idUser: null },
      { idBooking: null, idTicket: 9, idUser: null },
      { idBooking: null, idTicket: 9, idUser: null },
      { idBooking: null, idTicket: 9, idUser: null },
      { idBooking: null, idTicket: 9, idUser: null },
      { idBooking: null, idTicket: 9, idUser: null },
      // ticket 10 idOwner 8 22seats
      { idBooking: null, idTicket: 10, idUser: null },
      { idBooking: null, idTicket: 10, idUser: null },
      { idBooking: null, idTicket: 10, idUser: null },
      { idBooking: null, idTicket: 10, idUser: null },
      { idBooking: null, idTicket: 10, idUser: null },
      { idBooking: null, idTicket: 10, idUser: null },
      { idBooking: null, idTicket: 10, idUser: null },
      { idBooking: null, idTicket: 10, idUser: null },
      { idBooking: null, idTicket: 10, idUser: null },
      { idBooking: null, idTicket: 10, idUser: null },
      { idBooking: null, idTicket: 10, idUser: null },
      { idBooking: null, idTicket: 10, idUser: null },
      { idBooking: null, idTicket: 10, idUser: null },
      { idBooking: null, idTicket: 10, idUser: null },
      { idBooking: null, idTicket: 10, idUser: null },
      { idBooking: null, idTicket: 10, idUser: null },
      { idBooking: null, idTicket: 10, idUser: null },
      { idBooking: null, idTicket: 10, idUser: null },
      { idBooking: null, idTicket: 10, idUser: null },
      { idBooking: null, idTicket: 10, idUser: null },
      { idBooking: null, idTicket: 10, idUser: null },
      { idBooking: null, idTicket: 10, idUser: null },
      // ticket 2 idOwner 1 9seats
      { idBooking: null, idTicket: 2, idUser: null },
      { idBooking: null, idTicket: 2, idUser: null },
      { idBooking: null, idTicket: 2, idUser: null },
      { idBooking: null, idTicket: 2, idUser: null },
      { idBooking: null, idTicket: 2, idUser: null },
      { idBooking: null, idTicket: 2, idUser: null },
      { idBooking: null, idTicket: 2, idUser: null },
      { idBooking: null, idTicket: 2, idUser: null },
      { idBooking: null, idTicket: 2, idUser: null },
      // ticket 7 idOwner 2 32seats
      { idBooking: null, idTicket: 7, idUser: null },
      { idBooking: null, idTicket: 7, idUser: null },
      { idBooking: null, idTicket: 7, idUser: null },
      { idBooking: null, idTicket: 7, idUser: null },
      { idBooking: null, idTicket: 7, idUser: null },
      { idBooking: null, idTicket: 7, idUser: null },
      { idBooking: null, idTicket: 7, idUser: null },
      { idBooking: null, idTicket: 7, idUser: null },
      { idBooking: null, idTicket: 7, idUser: null },
      { idBooking: null, idTicket: 7, idUser: null },
      { idBooking: null, idTicket: 7, idUser: null },
      { idBooking: null, idTicket: 7, idUser: null },
      { idBooking: null, idTicket: 7, idUser: null },
      { idBooking: null, idTicket: 7, idUser: null },
      { idBooking: null, idTicket: 7, idUser: null },
      { idBooking: null, idTicket: 7, idUser: null },
      { idBooking: null, idTicket: 7, idUser: null },
      { idBooking: null, idTicket: 7, idUser: null },
      { idBooking: null, idTicket: 7, idUser: null },
      { idBooking: null, idTicket: 7, idUser: null },
      { idBooking: null, idTicket: 7, idUser: null },
      { idBooking: null, idTicket: 7, idUser: null },
      { idBooking: null, idTicket: 7, idUser: null },
      { idBooking: null, idTicket: 7, idUser: null },
      { idBooking: null, idTicket: 7, idUser: null },
      { idBooking: null, idTicket: 7, idUser: null },
      { idBooking: null, idTicket: 7, idUser: null },
      { idBooking: null, idTicket: 7, idUser: null },
      { idBooking: null, idTicket: 7, idUser: null },
      { idBooking: null, idTicket: 7, idUser: null },
      { idBooking: null, idTicket: 7, idUser: null },
      { idBooking: null, idTicket: 7, idUser: null },
      // ticket 11 idOwner 7 9seats
      { idBooking: null, idTicket: 11, idUser: null },
      { idBooking: null, idTicket: 11, idUser: null },
      { idBooking: null, idTicket: 11, idUser: null },
      { idBooking: null, idTicket: 11, idUser: null },
      { idBooking: null, idTicket: 11, idUser: null },
      { idBooking: null, idTicket: 11, idUser: null },
      { idBooking: null, idTicket: 11, idUser: null },
      { idBooking: null, idTicket: 11, idUser: null },
      { idBooking: null, idTicket: 11, idUser: null },
      // ticket 12 idOwner 7 9seats
      { idBooking: null, idTicket: 12, idUser: null },
      { idBooking: null, idTicket: 12, idUser: null },
      { idBooking: null, idTicket: 12, idUser: null },
      { idBooking: null, idTicket: 12, idUser: null },
      { idBooking: null, idTicket: 12, idUser: null },
      { idBooking: null, idTicket: 12, idUser: null },
      { idBooking: null, idTicket: 12, idUser: null },
      { idBooking: null, idTicket: 12, idUser: null },
      { idBooking: null, idTicket: 12, idUser: null },
      // ticket 13 idOwner 7 9seats
      { idBooking: null, idTicket: 13, idUser: null },
      { idBooking: null, idTicket: 13, idUser: null },
      { idBooking: null, idTicket: 13, idUser: null },
      { idBooking: null, idTicket: 13, idUser: null },
      { idBooking: null, idTicket: 13, idUser: null },
      { idBooking: null, idTicket: 13, idUser: null },
      { idBooking: null, idTicket: 13, idUser: null },
      { idBooking: null, idTicket: 13, idUser: null },
      { idBooking: null, idTicket: 13, idUser: null },
      // ticket 14 idOwner 8 22seats
      { idBooking: null, idTicket: 14, idUser: null },
      { idBooking: null, idTicket: 14, idUser: null },
      { idBooking: null, idTicket: 14, idUser: null },
      { idBooking: null, idTicket: 14, idUser: null },
      { idBooking: null, idTicket: 14, idUser: null },
      { idBooking: null, idTicket: 14, idUser: null },
      { idBooking: null, idTicket: 14, idUser: null },
      { idBooking: null, idTicket: 14, idUser: null },
      { idBooking: null, idTicket: 14, idUser: null },
      { idBooking: null, idTicket: 14, idUser: null },
      { idBooking: null, idTicket: 14, idUser: null },
      { idBooking: null, idTicket: 14, idUser: null },
      { idBooking: null, idTicket: 14, idUser: null },
      { idBooking: null, idTicket: 14, idUser: null },
      { idBooking: null, idTicket: 14, idUser: null },
      { idBooking: null, idTicket: 14, idUser: null },
      { idBooking: null, idTicket: 14, idUser: null },
      { idBooking: null, idTicket: 14, idUser: null },
      { idBooking: null, idTicket: 14, idUser: null },
      { idBooking: null, idTicket: 14, idUser: null },
      { idBooking: null, idTicket: 14, idUser: null },
      { idBooking: null, idTicket: 14, idUser: null },
    ];
    items.forEach((item) => {
      item.createdAt = Sequelize.literal("NOW() ");
      item.updatedAt = Sequelize.literal("NOW() ");
    });
    return queryInterface.bulkInsert("Seats", items);
  },

  down: (queryInterface, Sequelize) => {
    return queryInterface.bulkDelete("Seats", null, {});
  },
};
